CREATE TABLE TBFISCAL(
CPF VARCHAR2(11) PRIMARY KEY NOT NULL,
NOME VARCHAR(30),
ENDERECO VARCHAR(40),
TELEFONE VARCHAR(12),
EMAIL VARCHAR(50),
CODIGO NUMBER(5,0)
LOCAL VARCHAR(30)
);

CREATE TABLE TBCANDIDATO(
CPF VARCHAR2(11) PRIMARY KEY NOT NULL,
INSCRICAO VARCHAR2(11) NOT NULL,
NOME VARCHAR(30),
ENDERECO VARCHAR(40),
TELEFONE VARCHAR(12),
EMAIL VARCHAR(30),
MEDIA NUMBER(2,2)
);

CREATE TABLE TBCONCURSO(
SIGLA VARCHAR2(4) PRIMARY KEY NOT NULL,
DESCRICAO VARCHAR2(255),
DATA VARCHAR2(12) NOT NULL,
TAXA_INSCRICAO NUMBER(6,2)
);

CREATE TABLE TBCONCURSO_FISCAL(
ID NUMBER(4) PRIMARY KEY NOT NULL,
CPF VARCHAR2(11) NOT NULL,
SIGLA VARCHAR2(4) NOT NULL
);