/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author feliperichter
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        MenuItemCandidato = new javax.swing.JMenuItem();
        MenuItemFiscal = new javax.swing.JMenuItem();
        MenuItemConcurso = new javax.swing.JMenuItem();
        MenuItemAlocarFiscal = new javax.swing.JMenuItem();
        MenuItemMontarProva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cadastro.setText("Cadastro");

        MenuItemCandidato.setText("Candidato");
        MenuItemCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCandidatoActionPerformed(evt);
            }
        });
        Cadastro.add(MenuItemCandidato);

        MenuItemFiscal.setText("Fiscal");
        MenuItemFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFiscalActionPerformed(evt);
            }
        });
        Cadastro.add(MenuItemFiscal);

        MenuItemConcurso.setText("Concurso");
        MenuItemConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConcursoActionPerformed(evt);
            }
        });
        Cadastro.add(MenuItemConcurso);

        MenuItemAlocarFiscal.setText("Alocar Fiscal");
        MenuItemAlocarFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAlocarFiscalActionPerformed(evt);
            }
        });
        Cadastro.add(MenuItemAlocarFiscal);

        MenuItemMontarProva.setText("Montar Prova");
        MenuItemMontarProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemMontarProvaActionPerformed(evt);
            }
        });
        Cadastro.add(MenuItemMontarProva);

        Menu.add(Cadastro);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCandidatoActionPerformed
        new GuiCandidato().setVisible(true);
    }//GEN-LAST:event_MenuItemCandidatoActionPerformed

    private void MenuItemFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFiscalActionPerformed
        new GuiFiscal().setVisible(true);
    }//GEN-LAST:event_MenuItemFiscalActionPerformed

    private void MenuItemConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConcursoActionPerformed
         new GuiConcurso().setVisible(true);
    }//GEN-LAST:event_MenuItemConcursoActionPerformed

    private void MenuItemAlocarFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAlocarFiscalActionPerformed
         //new GuiAlocarFiscal().setVisible(true);
    }//GEN-LAST:event_MenuItemAlocarFiscalActionPerformed

    private void MenuItemMontarProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemMontarProvaActionPerformed
         new GuiProva().setVisible(true);
    }//GEN-LAST:event_MenuItemMontarProvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MenuItemAlocarFiscal;
    private javax.swing.JMenuItem MenuItemCandidato;
    private javax.swing.JMenuItem MenuItemConcurso;
    private javax.swing.JMenuItem MenuItemFiscal;
    private javax.swing.JMenuItem MenuItemMontarProva;
    // End of variables declaration//GEN-END:variables
}
